"""The uniform engine contract (v1.0.0): EVERY L0 engine returns an `ok` envelope whose `data`
carries a valid graded `finding`. This validates a representative output from each of the nine
engines against schemas/envelope.schema.json — proving one stable contract across the core.
"""
import json
from pathlib import Path

import pytest

jsonschema = pytest.importorskip("jsonschema")
from referencing import Registry, Resource  # noqa: E402
from jsonschema import Draft202012Validator  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
SCHEMAS = ROOT / "schemas"
ENVELOPES = ROOT / "tests" / "fixtures" / "envelopes"

# One representative output per engine (generated by running the engine; committed as fixtures).
ENGINES = [
    "power_sample_size", "stat_run", "guideline_check", "citation_parse",
    "epistemic_grade", "injection_scan", "grimmer", "interim_boundaries",
]


def _validator():
    resources = [
        (s.name, Resource.from_contents(json.loads(s.read_text())))
        for s in SCHEMAS.glob("*.json")
    ]
    registry = Registry().with_resources(resources)
    schema = json.loads((SCHEMAS / "envelope.schema.json").read_text())
    return Draft202012Validator(schema, registry=registry)


def test_every_engine_has_an_envelope_fixture():
    present = {p.stem.replace(".out", "") for p in ENVELOPES.glob("*.out.json")}
    assert set(ENGINES) <= present, f"missing envelope fixtures: {set(ENGINES) - present}"


@pytest.mark.parametrize("engine", ENGINES)
def test_engine_output_conforms_to_envelope(engine):
    out = json.loads((ENVELOPES / f"{engine}.out.json").read_text())
    _validator().validate(out)               # status + data + valid finding
    assert out["status"] == "ok"
    assert "finding" in out["data"]
